# Generated by Django 5.0.1 on 2024-01-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='characters',
            field=models.ManyToManyField(null=True, related_name='movies', to='ex10.people'),
        ),
    ]
