# Generated by Django 5.0.1 on 2024-01-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0002_alter_movies_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
