# Generated by Django 5.0.1 on 2024-01-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0004_alter_planets_created_alter_planets_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='characters',
            field=models.ManyToManyField(related_name='movies', to='ex10.people'),
        ),
    ]
