# Generated by Django 5.0.2 on 2024-02-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='crated',
            new_name='created',
        ),
    ]
