# Generated by Django 5.0.1 on 2024-01-25 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planets'),
        ),
    ]
