from .articles import ArticlesView
from .home import HomeView
from .user_login import UserLoginView
from .user_logout import UserLogoutView
from .publications import PublicationsView
from .publish import PublishView
from .article_detail import ArticleDetailView
from .favorites import FavoritesView
from .register import UserRegisterView